;<?php
;die();
;/*
[STRING]
	ABOUT					= "Περί"
	ADMIN					= "Διαχείριση"
	CREATE					= "Δημιουργία"
	DATABASES				= "Βάσεις δεδομένων"
	DELETE					= "Διαγραφή"
	DOWNLOAD				= "Κατέβασμα"
	ERROR_FILE_READ			= "Δεν ήταν δυνατή η ανάγνωση του αρχείου"
	ERROR_FILE_DELETE		= "Δεν ήταν δυνατή η διαγραφή του αρχείου"
	ERROR_FILE_MISSING		= "Δεν υπάρχει το συγκεκριμένο αρχείο"
	ERROR_FILE_SAVE			= "Δεν ήταν δυνατή η αποθήκευση του αρχείου"
	ERROR_FILE_STRUCTURE	= "Η δομή του αρχείου δεν είναι σωστή, χρησιμοποιείστε το πρότυπο"
	ERROR_PIN				= "Λάθος PIN και PIN διαχειριστή"
	ERROR_PIN_EMPTY			= "Το PIN μέσα στο αρχείο είναι κενό"
	ERROR_PIN_DIFFERENT		= "Το παλιό PIN με το νέο είναι διαφορετικό"
	ERROR_PIN_MISSING		= "Δεν υπάρχει PIN μέσα στο αρχείο"
	ERROR_PIN_EXISTS		= "Υπάρχει ήδη αποθηκευμένο κουίζ με το ίδιο PIN"
	FILE_DELETED			= "Το αρχείο διαγράφηκε με επιτυχία"
	FILE_UPDATE				= "Το αρχείο ενημερώθηκε με επιτυχία"
	FILE_UPLOAD				= "Το αρχείο αποθηκεύτηκε με επιτυχία"
	FROM					= "από"
	HOME					= "Αρχική σελίδα"
	HELP					= "Βοήθεια"
	IP						= "IP"
	INSTRUCTIONS			= "Οδηγίες"
	LANGUAGE				= "Γλώσσα"
	PIN_ID					= "Μητρώο"
	PIN_ID_HELP				= "Εισάγετε το μητρώο σας"
	PIN_QUIZ				= "PIN"
	PIN_QUIZ_ADMIN			= "PIN διαχειριστή"
	PIN_QUIZ_HELP			= "Εισάγετε το PIN της εξέτασης"
	QUESTIONS				= "Ερωτήσεις"
	QUESTIONS_COMPLETED		= "Ποσοστό ολοκλήρωσης"
	QUESTIONS_PER_QUIZ		= "Ερωτήσεις ανα τέστ"
	QUESTIONS_UNANSWERED	= "Αναπάντητες ερωτήσεις"
	RETURN					= "Επιστροφή"
	RESULTS					= "Αποτελέσματα"
	SOUND					= "Ήχος"
	START					= "Έναρξη"
	SUBMIT					= "Υποβολή"
	SUBMIT_QUESTION			= "Είστε σίγουροι ότι θέλετε να υποβάλλετε οριστικά τις απαντήσεις σας;"
	SUBMIT_TIME				= "Χρόνος υποβολής"
	TEMPLATE				= "Πρότυπο"
	UPDATE					= "Ενημέρωση"
	VERSION					= "Έκδοση"
;*/
;?>
